name: stale repo identifier local

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  packages: read

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run stale_repos tool
      id: stale-repos
      uses: akbast/stale-repos@main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: akbas-orga
        INACTIVE_DAYS: 1

    - name: Print output of stale_repos tool
      run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"
    - uses: actions/github-script@v6
      with:
        script: |
          const repos = JSON.parse(${{ steps.stale-repos.outputs.inactiveRepos }});
          for (const repo of repos) {
            console.log(repo);
            const issue = await github.rest.issues.create({
              owner: akbast,
              repo: stale-repos,
              title: 'Stale repo' + repo.url,
              body: 'This repo is stale. Please contact the owner to make it active again.',
            });
            console.log(issue);
          }
        github-token: ${{ secrets.GH_TOKEN }}
